Oct 20 23:46:07 jamesmacbookpro main[87050]: main Error
Oct 20 23:46:07 jamesmacbookpro main[87050]: 2016-10-20 23:46:07.862 main[87050:853412] main Error
Oct 20 23:46:13 jamesmacbookpro main[87050]: Traceback (most recent call last):
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "/Users/james/projects/afit/py2app/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module>
Oct 20 23:46:13 jamesmacbookpro main[87050]:     _run()
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "/Users/james/projects/afit/py2app/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run
Oct 20 23:46:13 jamesmacbookpro main[87050]:     exec(compile(source, path, 'exec'), globals(), globals())
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "/Users/james/projects/afit/py2app/dist/main.app/Contents/Resources/main.py", line 4, in <module>
Oct 20 23:46:13 jamesmacbookpro main[87050]:     from PyQt5.QtWidgets import QApplication, QLabel
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "PyQt5/QtWidgets.pyc", line 14, in <module>
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "PyQt5/QtWidgets.pyc", line 10, in __load
Oct 20 23:46:13 jamesmacbookpro main[87050]:   File "imp.pyc", line 342, in load_dynamic
Oct 20 23:46:13 jamesmacbookpro main[87050]: ImportError: dlopen(/Users/james/projects/afit/py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
Oct 20 23:46:13 jamesmacbookpro main[87050]:   Referenced from: /Users/james/projects/afit/py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so
Oct 20 23:46:13 jamesmacbookpro main[87050]:   Reason: image not found
